# fly.toml app configuration file generated for beaded-muse-backend on 2025-04-17T05:04:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beaded-muse-backend'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
